#cloud-config

hostname: ${hostname}

fs_setup:
  - label: pihole-data
    filesystem: ext4
    device: /dev/vdb

mounts:
  - [vdb, /mnt/persistent]

write_files:
  - path: /opt/pihole-ansible/requirements.yml
    content: ${requirements}
    encoding: b64
  - path: /opt/pihole-ansible/playbook.yml
    content: ${playbook}
    encoding: b64
  - path: /opt/pihole-ansible/vars.yml
    mode: 0600
    content: |
      ${indent(6, custom_config)}

packages:
  - python3-netaddr

runcmd:
  - mkdir -p /mnt/persistent/etc/pihole
  - ln -s /mnt/persistent/etc/pihole /etc/pihole
  - cd /opt/pihole-ansible
  - export ANSIBLE_ROLES_PATH=$PWD/roles
  - export ANSIBLE_COLLECTIONS_PATH=$PWD/collections
  - mkdir $ANSIBLE_ROLES_PATH $ANSIBLE_COLLECTIONS_PATH
  - ansible-galaxy install -r requirements.yml
  - ansible-galaxy install -r roles/pihole/requirements.yml
  - ansible-playbook playbook.yml
