#cloud-config

hostname: ${hostname}
# do not resolve hostname to 127.0.0.1, because it's caught up by the DNS service
manage_etc_hosts: false

fs_setup:
  - label: pihole-data
    filesystem: ext4
    device: /dev/vdb

mounts:
  - [vdb, /mnt/persistent]

write_files:
  - path: /opt/pihole-ansible/requirements.yml
    content: ${requirements}
    encoding: b64
  - path: /opt/pihole-ansible/playbook.yml
    content: ${playbook}
    encoding: b64
  - path: /opt/pihole-ansible/vars.yml
    mode: 0600
    content: |
      ${indent(6, custom_config)}

runcmd:
  - mkdir -p /mnt/persistent/etc/pihole
  - ln -s /mnt/persistent/etc/pihole /etc/pihole
  - cd /opt/pihole-ansible
  - ansible-galaxy install -r requirements.yml
  - ansible-playbook playbook.yml
